import "./admins.css";
import NavBar from "./admin/ui/NavBar";
import SideBar from "./admin/ui/SideBar";
import { Toaster } from "react-hot-toast";
import "@uploadthing/react/styles.css";

export const metadata = {
  title: "Coaching-Management-System  Admin Panel",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-[80px] fixed inset-x-0 top-0 z-50">
          <NavBar />
        </div>
        <div className=" md:flex h-full w-56 fixed mt-20 flex-col z-40">
          <SideBar />
        </div>
        <main className="md:pl-56 pt-[80px]">{children}</main>
      </body>
    </html>
  );
}
